# Generated by Django 4.2.3 on 2023-07-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='picture_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='picture_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
